// vue crash course/task-tracker-application/src/components/AddTask.vue
<template>
  <form v-on:submit="onSubmit" class="add-task">
    <div class="form-control">
      <label>Task</label>
      <input type="text" v-model="text" name="text" placeholder="Add Task" />
    </div>
    <div class="form-control">
      <label>Day & Time</label>
      <input
        type="text"
        v-model="day"
        name="day"
        placeholder="Add Day & Time"
      />
    </div>
    <div class="form-control form-control-check">
      <label>Set Reminder</label>
      <input
        type="checkbox"
        v-model="reminder"
        name="reminder"
        placeholder="Add Day & Time"
      />
    </div>
    <input type="submit" value="Save Task" class="btn btn-block" />
  </form>
</template>

<script>
export default {
  name: "AddTask",
  data() {
    return {
      text: "",
      day: "",
      reminder: false,
    };
  },
  methods: {
    onSubmit(e) {
      e.preventDefault();

      if (!this.text) {
        alert("Please add a task");
        return;
      }

      const newTask = {
        // id: Math.floor(Math.random() * 100000), // gets automatically added by json-server now
        text: this.text,
        day: this.day,
        reminder: this.reminder,
      };
      this.$emit("add-task", newTask);

      //clear form
      this.text = "";
      this.day = "";
      this.reminder = false;
    },
  },
};
</script>

<style scoped>
.add-task {
  margin-bottom: 40px;
}
.form-control {
  margin: 20px 0;
}
.form-control label {
  display: block;
}
.form-control input {
  width: 100%;
  padding: 0.5rem;
  font-size: 1rem;
}
.form-control-check {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.form-control-check input {
  flex-basis: 0;
  height: 1rem;
}
</style>

// angular/angular-crash/src/app/components/add-task/add-task.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import {Task} from '../../Task'
@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css']
})
export class AddTaskComponent {
  @Output() onAddTask: EventEmitter<Task> = new EventEmitter()
  
  text: string = null!;
  day: string = null!;
  reminder: boolean = false;

  onSubmit() {
    if (!this.text) {
      alert('Please add a task.')
      return;
    }
    const newTask = {
      text: this.text,
      day: this. day,
      reminder: this.reminder
    }

    this.onAddTask.emit(newTask);

    this.text = '';
    this.day = '';
    this.reminder = false
  }
}

<form class="add-form" (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="text">Task</label>
        <input type="text" name="text" [(ngModel)]="text" id="text" placeholder="Add Task ">
    </div>
    <div class="form-control">
        <label for="day">Day & Time</label>
        <input type="text" name="day" [(ngModel)]="day" id="day" placeholder="Add Day & Time ">
    </div>
    <div class="form-control form-control-check">
        <label for="reminder">Set Reminder</label>
        <input type="checkbox" name="reminder" [(ngModel)]="reminder" id="reminder">
    </div>
    <input type="submit" value="Save Task" class="btn btn-block">
</form>
